
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = 'v~\xf6\xdf\n\xfdn\n\x00\xb2\xfc)\x9d\xa8E\xd0'
    
_lr_action_items = {'RPAREN':([4,7,9,11,12,13,14,17,18,],[-2,14,-4,-10,-9,-1,-3,-5,-6,]),'HAN':([6,],[12,]),'PIPE':([4,9,11,12,13,14,18,],[-2,15,-10,-9,-1,-3,-6,]),'TAG':([0,5,15,16,],[3,8,8,3,]),'COLON':([2,3,8,10,],[6,-7,-8,16,]),'LPAREN':([2,3,],[5,-7,]),'NUM':([6,],[11,]),'$end':([1,4,11,12,13,14,],[0,-2,-10,-9,-1,-3,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'han':([6,],[13,]),'elm':([0,16,],[1,18,]),'semGroup':([5,15,],[7,17,]),'tag':([0,16,],[2,2,]),'pars':([2,],[4,]),'semelm':([5,15,],[9,9,]),'sem':([5,15,],[10,10,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> elm","S'",1,None,None,None),
  ('elm -> tag COLON han','elm',3,'p_elm_han','treelex.py',58),
  ('elm -> tag pars','elm',2,'p_elm_col','treelex.py',66),
  ('pars -> LPAREN semGroup RPAREN','pars',3,'p_col_semGroup','treelex.py',74),
  ('semGroup -> semelm','semGroup',1,'p_semGroup_sem','treelex.py',80),
  ('semGroup -> semelm PIPE semGroup','semGroup',3,'p_semGroup_semGroup','treelex.py',87),
  ('semelm -> sem COLON elm','semelm',3,'p_sem_elm','treelex.py',95),
  ('tag -> TAG','tag',1,'p_tagval','treelex.py',103),
  ('sem -> TAG','sem',1,'p_semval','treelex.py',108),
  ('han -> HAN','han',1,'p_hanval','treelex.py',113),
  ('han -> NUM','han',1,'p_nanval','treelex.py',118),
]
